name: Build and Test

on:
  push:
    branches:
      - '*'

jobs:
  build_linux:
    name: Build and test on Linux
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        otp: ['26.2', '27.3', '28.0']
        elixir: ['1.16.3', '1.17.1', '1.18.4']
        exclude:
          - otp: '26.2'
            elixir: '1.18.4'
          - otp: '27.3'
            elixir: '1.16.3'
          - otp: '28.0'
            elixir: '1.16.3'
          - otp: '28.0'
            elixir: '1.17.1'
    env:
      MIX_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          install-hex: true
          install-rebar: true

      - name: Setup Elixir Project
        run: mix deps.get

      - name: Check format
        run: mix format --check-formatted

      - name: Run Tests
        run: mix test --warnings-as-errors
